export const ActivityAction = {
  // Project
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",
  PROJECT_RESTORED: "PROJECT_RESTORED",
  PROJECT_DELETED: "PROJECT_DELETED",

  // Project Member
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",

  // Task
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_MOVED: "TASK_MOVED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_DELETED: "TASK_DELETED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UNASSIGNED: "TASK_UNASSIGNED",

  // Kanban Column
  COLUMN_CREATED: "COLUMN_CREATED",
  COLUMN_UPDATED: "COLUMN_UPDATED",
  COLUMN_DELETED: "COLUMN_DELETED",
  COLUMN_REORDERED: "COLUMN_REORDERED",
} as const;

export type ActivityAction =
  (typeof ActivityAction)[keyof typeof ActivityAction];
